### ISSUE TITLE
Tests for Zesty Zapus

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite-installers#444]
## Summary

Since 16.10, systemd has been both for system and user sessions (startup applications etc). No more upstart.

We've fixed #440 and as of now, released it in ka-lite-proposed

I think we should test our installers for 17.04 already, so we know if we're good.

@radinamatic - would you be able to do this?

**Comment by radinamatic** [comment]
Tested on Ubuntu 16.10, with installer [ka-lite-bundle_0.17.0-0ubuntu2_all.deb](https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite-proposed/+files/ka-lite-bundle_0.17.0-0ubuntu2_all.deb)

However, server is not starting at reboot:

![virtualbox_ubuntu 16 10_10_04_2017_14_21_48](https://cloud.githubusercontent.com/assets/1457929/24862548/54c190e6-1dfd-11e7-9a1e-49fbeba5098b.png)

![virtualbox_ubuntu 16 10_10_04_2017_14_22_05](https://cloud.githubusercontent.com/assets/1457929/24862569/60b895c0-1dfd-11e7-95cf-6d0b8be0ec56.png)

Tried checking `kalite.service` as suggested in [#5423](https://github.com/learningequality/ka-lite/issues/5423):

![virtualbox_ubuntu 16 10_10_04_2017_14_38_11](https://cloud.githubusercontent.com/assets/1457929/24862583/6c4e1db0-1dfd-11e7-9c3c-dcfcbc4d746d.png)

**Comment by benjaoming** [comment]
@radinamatic I'll get 16.10 running on a virtualbox and see what that's about.

**Comment by benjaoming** [comment]
Seems everything is fine with the latest 0.17.0-0ubuntu3 - which incidentally also contained a systemd fix, see #443

**Comment by radinamatic** [comment]
I tried again on Ubuntu 16.10 (latest with all the updates), with installer `ka-lite-bundle_0.17.0-0ubuntu3_all.deb`, but the server is still not starting at reboot.

![virtualbox_ubuntu 16 10_03_05_2017_15_57_13](https://cloud.githubusercontent.com/assets/1457929/25664732/ced7a6ce-301b-11e7-8c6f-0ae58a648606.png)

![virtualbox_ubuntu 16 10_03_05_2017_16_12_03](https://cloud.githubusercontent.com/assets/1457929/25664743/d613bed2-301b-11e7-8f2f-b912eb62b05c.png)

Am I missing something @benjaoming?

**Comment by benjaoming** [comment]
@radinamatic sorry I didn't properly explain. #440 is still open and that part is still broken. There's more explanation in that issue.

You can still start ka-lite with both `sudo service ka-lite start` and `sudo systemctl start ka-lite.service`

**Comment by radinamatic** [comment]
Starting it from terminal is not a problem, even simple `kalite start` works:

![virtualbox_ubuntu 16 10_04_05_2017_12_53_20](https://cloud.githubusercontent.com/assets/1457929/25700623/c448c64a-30c8-11e7-969d-6d2da3e0f5f5.png)

Maybe I'm not getting the real purpose of having a system service... 🤔 
My understanding was that the main benefit was so KA Lite could run from boot/startup, but if that's not working because of the broken stuff you investigated in #440, then we should amend the wording of the install configuration, because it is misleading:

![boot](https://cloud.githubusercontent.com/assets/1457929/25700733/43a15f7e-30c9-11e7-9f2c-ce2a15868a78.png)

Here it states that the service is started automatically, and that's not the case atm, at least on 16.10.

![boot2](https://cloud.githubusercontent.com/assets/1457929/25700841/c6993b40-30c9-11e7-835c-ff605b52604e.png)

**Comment by benjaoming** [comment]
@radinamatic I can't work with the differences caused by systemd and explain them to users. Luckily, `service ka-lite` is still functional on systemd 15.04+ systems afaik.

> :thinking: My understanding was that the main benefit was so KA Lite could run from boot/startup, but if that's not working because of the broken stuff you investigated in #440, then we should amend the wording of the install configuration, because it is misleading:

I'll fix the startup script and leave the texts unchanged ;)

The purpose of having a system service, is so things get started and stopped when the system boots and shuts down.

**Comment by radinamatic** [comment]
> The purpose of having a system service, is so things get started and stopped when the system boots and shuts down.

Ok, so I wasn't so far off base after all... 😛 

> I'll fix the startup script and leave the texts unchanged ;)

If the startup script is fixed, no need to change the text! 😉
